### PR TITLE
Update ValueChanged event

### PR DESCRIPTION
**Pull request by Nuwanda22**
#### Fix untracked files
Removed files that were unnecessarily tracked.
ex) obj, bin, packages

#### Update ValueChanged event
Added event keyword to ValueChanged.

``` c#
// In SegmentedControl.cs
public event EventHandler<ValueChangedEventArgs> ValueChanged;

[EditorBrowsable(EditorBrowsableState.Never)]
public void SendValueChanged()
{
    ValueChanged?.Invoke(this, new ValueChangedEventArgs { SelectedIndex = this.SelectedSegment });
}
```

``` c#
// In SegmentedControlImplementation.cs
protected override void OnElementPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
{
	base.OnElementPropertyChanged(sender, e);
            
	switch (e.PropertyName)
	{
		case "Renderer":
                        Element.SendValueChanged();
			break;
		case "SelectedSegment":
			var option = (RadioButton)nativeControl.GetChildAt(Element.SelectedSegment);
                        option.Checked = true;
                        Element.SendValueChanged();
			break;
		//...		
	}
}
```

### CODE REVIEW

**Comment by dheif** [comment]
Could this be integrated in the main branch?

**Comment by Nuwanda22** [comment]
@dheif No problem.

**Comment by alexrainman** [comment]
Going to integrate this fix.

**Comment by Nuwanda22** [comment]
@alexrainman I fixed it.

**Comment by alexrainman** [comment]
@Nuwanda22 i can see that but i like it with ValueChangedEventArgs :)

**Comment by alexrainman** [comment]
@Nuwanda22 @dheif next release.

**Comment by Nuwanda22** [comment]
@alexrainman If I change it to use ValueChangedEventArgs, the existing code will not work, so I modified it. If you want, I'll change to use ValueChanged EventArgs.

**Comment by Nuwanda22** [comment]
Alternatively, I can create a new SegmentChanged event and obsolete the ValueChanged event.

Like this
``` csharp
[Obsolete("Use SegmentChanged instead")]
public event EventHandler ValueChanged;

public event EventHandler<SegmentChangedEventArgs> SegmentChanged;
```

**Comment by Nuwanda22** [comment]
Or like this. I think this way is better. [iOS Document](https://developer.xamarin.com/recipes/ios/standard_controls/segmented_button_control/configure_segments_(uisegmentedcontrol)/#Recipe)

``` csharp
void SegmentedControl_ValueChanged(object sender, EventArgs e)
{
    var control = sender as SegmentedControl;

    switch (control.SelectedSegment)
    {
        // ...
    }
}
```

**Pull request closed without merging**
